### ISSUE TITLE
The reproduction of RedQueen

### ISSUE THREAD

**Issue by ursulalujun** [kriti-hippo/red_queen#3]
Hello~
I use your open sourced data "Red_Qween_Attack/data/Red_Queen_Attack/llama3_7b_attack_data.json" to test LLaMA3-8B-instruct model. I just select the sample with turn 5, and input the query from the above file to the model LLaMA3-8B-instruct. According to your paper, I set temperature as 1. However, I figure the average ASR is 6.64%, which is much lower than your results (23.21%) shown in the following table: 
![image](https://github.com/user-attachments/assets/85fa827b-a097-4eeb-b918-66e42301b236)
Can you please help me check my experimental steps for any inconsistencies with yours, and can you describe in detail how you calculated the average ASR?

**Comment by 1171-jpg** [comment]
Solved via email by sharing the prompt and evaluation result of llama3-8b
